=== yaskachkov/omskkiosk/config/files/schema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="Identifier">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Za-z0-9-_]{1,32}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="Url">
        <xs:restriction base="xs:anyURI">
            <xs:pattern value="https?://.+"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="Coordinate">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d+(.\d*)+,\d+(.\d*)+"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="Location">
        <xs:all>
            <xs:element name="lat" type="xs:double"/>
            <xs:element name="lon" type="xs:double"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="LocationArray">
        <xs:sequence>
            <xs:element name="point" type="Location" minOccurs="2" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="FactArray">
        <xs:sequence>
            <xs:element name="fact" minOccurs="1" maxOccurs="unbounded" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="PlaceArray">
        <xs:sequence>
            <xs:element name="placeId" type="Identifier" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="UrlArray">
        <xs:sequence>
            <xs:element name="url" minOccurs="1" maxOccurs="unbounded" type="Url"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="About">
        <xs:sequence>
            <xs:element name="p" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Author">
        <xs:sequence>
            <xs:element name="name" minOccurs="1" maxOccurs="1" type="xs:string"/>
            <xs:element name="alias" minOccurs="1" maxOccurs="unbounded" type="xs:string"/>
            <xs:element name="url" minOccurs="0" maxOccurs="unbounded" type="Url"/>
            <xs:element name="about" type="About" minOccurs="0"/>
            <xs:element name="photoUrl" type="Url" minOccurs="0"/>
            <xs:element name="details" type="xs:string" minOccurs="0"/>
            <xs:element name="email" type="xs:string"  minOccurs="0"/>
            <xs:element name="vkLink" type="Url" minOccurs="0"/>
            <xs:element name="telegramLink" type="Url" minOccurs="0"/>
            <xs:element name="okLink" type="Url" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Picture">
        <xs:sequence>
            <xs:element name="url" minOccurs="1" maxOccurs="unbounded" type="Url"/>
            <xs:element name="author" minOccurs="0" maxOccurs="1" type="xs:string">
                <xs:key name="authorKey">
                    <xs:selector xpath=".//Author"/>
                    <xs:field xpath="OrderNumber"/>
                </xs:key>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="main" type="xs:boolean" default="false" />
    </xs:complexType>

    <xs:complexType name="PictureArray">
        <xs:sequence>
            <xs:element name="picture" minOccurs="0" maxOccurs="unbounded" type="Picture"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Place">
        <xs:all>
            <xs:element name="id" type="Identifier" minOccurs="1"/>
            <xs:element name="caption" type="xs:string" minOccurs="1"/>
            <xs:element name="pictures" type="PictureArray" minOccurs="1"/>
            <xs:element name="year" type="xs:string"/>
            <xs:element name="facts" type="FactArray" minOccurs="1"/>
            <xs:element name="location" type="Coordinate" maxOccurs="1"/>
            <xs:element name="address" type="xs:string" minOccurs="1"/>
            <xs:element name="description" type="xs:string"/>
            <xs:element name="externalLink" type="Url" minOccurs="1" nillable="true"/>
            <xs:element name="vkLink" type="Url" minOccurs="1" nillable="true"/>
            <xs:element name="okLink" type="Url" minOccurs="1" nillable="true"/>
            <xs:element name="telegramLink" type="Url" minOccurs="1" nillable="true"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="Places">
        <xs:sequence>
            <xs:element name="place" minOccurs="1" maxOccurs="unbounded" type="Place"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Authors">
        <xs:sequence>
            <xs:element name="author" minOccurs="1" maxOccurs="unbounded" type="Author"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Excursion">
        <xs:all>
            <xs:element name="id" type="Identifier" minOccurs="1"/>
            <xs:element name="caption" type="xs:string" minOccurs="1"/>
            <xs:element name="mainPictureUrl" type="Url" maxOccurs="1"/>
            <xs:element name="description" type="xs:string"/>
            <xs:element name="route" type="LocationArray"/>
            <xs:element name="places" type="PlaceArray"/>
            <xs:element name="mapCenter" type="Location" minOccurs="1"/>
            <xs:element name="zoom" type="xs:unsignedInt" minOccurs="1"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="Excursions">
        <xs:sequence minOccurs="1" maxOccurs="unbounded">
            <xs:element name="excursion" type="Excursion" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Topic">
        <xs:all>
            <xs:element name="id" type="Identifier" minOccurs="1"/>
            <xs:element name="caption" type="xs:string" minOccurs="1"/>
            <xs:element name="description" type="xs:string"/>
            <xs:element name="mainPictureUrl" type="Url" maxOccurs="1"/>
            <xs:element name="places" type="PlaceArray"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="Topics">
        <xs:sequence minOccurs="1" maxOccurs="unbounded">
            <xs:element name="topic" type="Topic" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Config">
        <xs:all>
            <xs:element name="places" type="Places" minOccurs="0" maxOccurs="1">
                <xs:unique name="uniquePlaces">
                    <xs:selector xpath="place/id"/>
                    <xs:field xpath="."/>
                </xs:unique>
            </xs:element>
            <xs:element name="excursions" type="Excursions" minOccurs="0" maxOccurs="1">
                <xs:unique name="uniqueExcursions">
                    <xs:selector xpath="excursion/id"/>
                    <xs:field xpath="."/>
                </xs:unique>
            </xs:element>
            <xs:element name="topics" type="Topics" minOccurs="0" maxOccurs="1">
                <xs:unique name="uniqueTopics">
                    <xs:selector xpath="topic/id"/>
                    <xs:field xpath="."/>
                </xs:unique>
            </xs:element>
            <xs:element name="authors" type="Authors" minOccurs="0" maxOccurs="1">
                <xs:unique name="uniqueAuthor">
                    <xs:selector xpath="author/alias"/>
                    <xs:field xpath="."/>
                </xs:unique>
            </xs:element>
        </xs:all>
    </xs:complexType>
    <xs:element name="config" type="Config"/>
</xs:schema>

=== yaskachkov/omskkiosk/config/files/topics.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd">
    <topics>
        <topic>
            <id>1</id>
            <caption>Памятники</caption>
            <description>Все памятники Омска</description>
            <mainPictureUrl>https://admomsk.ru/image/image_gallery?img_id=356094</mainPictureUrl>
            <places>
                <placeId>1</placeId>
                <placeId>2</placeId>
            </places>
        </topic>
        <topic>
            <id>2</id>
            <caption>Места для фотосессий</caption>
            <description>Красивые места нашего города</description>
            <mainPictureUrl>https://admomsk.ru/image/image_gallery?img_id=356094</mainPictureUrl>
            <places>
                <placeId>1</placeId>
                <placeId>2</placeId>
            </places>
        </topic>
    </topics>
</config>

=== yaskachkov/omskkiosk/config/files/authors.xml
<?xml version="1.0" encoding="UTF-8"?>
<config  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd" >
    <authors>
        <author>
            <name>Иванов Иван Иванович</name>
            <alias>IvanovII</alias>
            <about>
                <p>Образование ОмГУ</p>
                <p>Работа в конторе</p>
            </about>
            <photoUrl>https://images.unsplash.com/photo-1582266255765-fa5cf1a1d501?ixlib=rb-4.0.3&amp;ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&amp;auto=format&amp;fit=crop&amp;w=2370&amp;q=80</photoUrl>
        </author>
        <author>
            <name>Петров Петр Петрович</name>
            <alias>PetrovPP</alias>
            <url>https://ya.ru/</url>
        </author>
    </authors>
</config>
